# Generated by Django 2.0 on 2019-08-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_recoverpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoverpassword',
            name='key',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
