# Generated by Django 2.0 on 2019-03-18 18:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_feedbackmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmail',
            name='sent',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
