# Generated by Django 2.0 on 2019-03-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_feedbackmail_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmail',
            name='subject',
            field=models.CharField(default='lmao', max_length=1000),
            preserve_default=False,
        ),
    ]
