# Generated by Django 2.0 on 2019-05-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20190504_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamekey',
            name='name',
            field=models.CharField(default='aaa', max_length=200),
            preserve_default=False,
        ),
    ]
