# Generated by Django 2.2.1 on 2019-06-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_gamekey_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamekey',
            name='status',
            field=models.CharField(choices=[('WAITING', 'WAITING'), ('PLAYING', 'PLAYING'), ('ENDING', 'ENDING')], default='ENDING', max_length=20),
            preserve_default=False,
        ),
    ]
