# Generated by Django 2.0 on 2019-07-27 12:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_userprofile_userprofilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilepicture',
            name='picture',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='profpicture'),
        ),
    ]
