# Generated by Django 2.0 on 2019-08-05 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_userprofile_background'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileGameBackground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.CharField(choices=[('Blue', 'blue'), ('Deep cyan', 'deepcyan'), ('Gray', 'gray'), ('Green', 'green'), ('Violet', 'violet')], default='blue', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='background',
        ),
        migrations.AddField(
            model_name='userprofilegamebackground',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.UserProfile'),
        ),
    ]
