# Generated by Django 2.0 on 2019-08-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_auto_20190805_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilegamebackground',
            name='background',
            field=models.CharField(choices=[('blue', 'Blue'), ('deepcyan', 'Deep cyan'), ('gray', 'Gray'), ('green', 'Green'), ('violet', 'Violet')], default='blue', max_length=100),
        ),
    ]
